options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlsecpix-456600/ml-metrics-exporter:latest', '.']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlsecpix-456600/ml-metrics-exporter:latest']

images:
  - 'gcr.io/mlsecpix-456600/ml-metrics-exporter:latest'