# Manifest do Kubernetes - inference-service.yaml
# Autor: Luana Gonçalves
# Data: Abril 2025

apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: mlsecops-fraud-detection
  labels:
    app: fraud-detection
    component: inference
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fraud-detection
    component: inference