global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ml-metrics-exporter"
    static_configs:
      - targets: ["ml-metrics-exporter.monitoring.svc.cluster.local:8080"]